// Generated By LeetSouls
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int valueAfterKSeconds(int n, int k)
    {
    }
};

int main()
{

    Solution leetSouls;
    int n1 = 4;
    int k1 = 5;
    int output_1 = 56;
    if (leetSouls.valueAfterKSeconds(n1, k1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    int n2 = 5;
    int k2 = 3;
    int output_2 = 35;
    if (leetSouls.valueAfterKSeconds(n2, k2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}