// Generated By LeetSouls
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int maxTotalReward(vector<int> &rewardValues)
    {
    }
};

int main()
{

    Solution leetSouls;
    vector<int> rewardValues1 = {1, 1, 3, 3};
    int output_1 = 4;
    if (leetSouls.maxTotalReward(rewardValues1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    vector<int> rewardValues2 = {1, 6, 4, 3, 2};
    int output_2 = 11;
    if (leetSouls.maxTotalReward(rewardValues2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}